// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameAPI.Data;

#nullable disable

namespace VideoGameAPI.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    [Migration("20251029130848_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameAPI.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "Insomania",
                            Platform = "PS5",
                            Publisher = "Sony",
                            Title = "Spiderman"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "T2T",
                            Platform = "Xbox",
                            Publisher = "Microsoft",
                            Title = "Knight War"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "RedToken",
                            Platform = "Mobile",
                            Publisher = "Bonarat",
                            Title = "Clash of Clans"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
